version: '3.5'

networks:
  react-front-tier:
    name: react-thedelta-io-net

services:
  react-thedelta:
    image: react-thedelta-io:1.10
    build:
      context: .
    container_name: thedelta-react-io
    expose:
      - 80
    ports:
      - 8080:80
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - react-front-tier
