version: '3.5'

networks:
  react-front-tier:
    name: react-the-delta-io-net

services:
  react-the-delta:
    image: react-the-delta-io:1.10
    build:
      context: .
    container_name: the-delta-react-io
    expose:
      - 80
    ports:
      - 8080:80
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - react-front-tier
